resource "aws_db_subnet_group" "main" {
  name       = local.name
  subnet_ids = aws_subnet.private[*].id
}

resource "aws_db_instance" "main" {
  identifier     = local.name
  engine         = "postgres"
  engine_version = "16"
  instance_class = var.db_instance_class

  allocated_storage     = var.db_allocated_storage_gb
  max_allocated_storage = var.db_allocated_storage_gb * 5
  storage_type          = "gp3"
  storage_encrypted     = true

  db_name  = "deltabt"
  username = "deltabt"

  # The password is generated by RDS and stored in Secrets Manager. It never
  # appears in Terraform state, in this repository, or in an environment
  # variable -- which is what "do not put the database password in Git"
  # actually requires. The alternative, random_password, writes the secret
  # into state in plaintext.
  manage_master_user_password = true

  # OFF. The bots use the master password (deploy/aws/run.sh, run_live.sh).
  #
  # IAM database authentication needs "between 300 and 1000 MiB extra memory"
  # (AWS). On this db.t4g.micro, with ~120 MiB free, enabling it on 2026-09-17
  # pushed swap from ~75 to ~340 MiB and every token login timed out and was
  # denied -- while the same instance served three running paper experiments.
  # It was disabled by CLI the same day; this keeps Terraform from turning it
  # back on at the next maintenance window.
  #
  # Re-enable only on an instance class with the memory, and together with
  # DB_IAM_AUTH in deploy/docker/Dockerfile.live. tests/live_exec/
  # test_live_db_auth.py fails if the three disagree.
  iam_database_authentication_enabled = false

  db_subnet_group_name   = aws_db_subnet_group.main.name
  vpc_security_group_ids = [aws_security_group.db.id]
  publicly_accessible    = false

  backup_retention_period = var.db_backup_retention_days
  backup_window           = "18:00-19:00" # ~23:30 IST, outside the busiest hours
  maintenance_window      = "sun:19:30-sun:20:30"
  copy_tags_to_snapshot   = true

  # The experiment database is the deliverable. Deleting it by accident loses
  # evidence that cannot be regenerated.
  deletion_protection       = var.db_deletion_protection
  skip_final_snapshot       = false
  final_snapshot_identifier = "${local.name}-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  performance_insights_enabled = false # not free on t4g.micro
  auto_minor_version_upgrade   = true
  apply_immediately            = false

  lifecycle {
    # Otherwise every plan shows a diff, because the identifier embeds a
    # timestamp evaluated at plan time.
    ignore_changes = [final_snapshot_identifier]

    # The last line of defence. deletion_protection can be flipped off in one
    # apply; this makes Terraform refuse to plan the destroy at all, so losing
    # a 30-day dataset takes a deliberate code change and a review.
    prevent_destroy = true
  }
}
